apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: docs
  name: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: docs
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: docs
    spec:
      containers:
      - command:
        - sh
        - /src/cfgov-refresh/docker/docs/entrypoint.sh
        env:
        - name: LANG
          value: en_US.utf8
        - name: LC_ALL
          value: en_US.utf8
        image: docs
        imagePullPolicy: ""
        name: docs
        ports:
        - containerPort: 8888
        resources: {}
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /src/cfgov-refresh
          name: docs-claim0
        workingDir: /src/cfgov-refresh
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: docs-claim0
        persistentVolumeClaim:
          claimName: docs-claim0
status: {}
