export const categoryDetails = [
  {
    step: 'Beginning Balance',
    category: 'Checking Account',
    screenNumber: 0,
    nextButtonText: ``,
    prevButtonText: ``,
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,

    pageImage: '/static/apps/mmt-my-money-calendar/img/icon-job.png',
    subtitle: 'Lets look at your checking account',
    description: '',
    nextPaymentDueDateLabel: '',
    nextPaymentAmountLabel: 'What is the balance?',
  },
  {
    step: 'Beginning Balance',
    category: 'Savings Account',
    screenNumber: 0,
    nextButtonText: ``,
    prevButtonText: ``,
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,
    pageImage: '/static/apps/mmt-my-money-calendar/img/icon-job.png',
    subtitle: 'Lets look at your Savings Account',
    description: '',
    nextPaymentDueDateLabel: '',
    nextPaymentAmountLabel: 'Whats the balance?',
  },
  {
    step: 'Beginnning Balance',
    category: 'Cash',
    screenNumber: 0,
    nextButtonText: ``,
    prevButtonText: ``,
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,
    pageImage: '/static/apps/mmt-my-money-calendar/img/icon-job.png',
    subtitle: 'Do you have any cash on hand?',
    description: '',
    nextPaymentDueDateLabel: '',
    nextPaymentAmountLabel: 'How much?',
  },
  {
    step: 'Beginning Balance',
    category: 'Prepaid Cards',
    screenNumber: 0,
    nextButtonText: ``,
    prevButtonText: ``,
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,
    pageImage: '/static/apps/mmt-my-money-calendar/img/icon-job.png',
    subtitle: 'Sometimes people have gas or grocery prepaid cards.  Lets count them!',
    description: '',
    nextPaymentDueDateLabel: '',
    nextPaymentAmountLabel: 'How much do you have in prepaid cards?',
  },
  {
    step: 'Beginning Balance',
    category: 'Other',
    screenNumber: 0,
    nextButtonText: ``,
    prevButtonText: ``,
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,
    pageImage: '/static/apps/mmt-my-money-calendar/img/icon-job.png',
    subtitle: 'Do you have any other forms of cash',
    description: '',
    nextPaymentDueDateLabel: '',
    nextPaymentAmountLabel: 'How much is that worth?',
  },
  {
    step: 'Income',
    category: 'Paycheck',
    screenNumber: 0,
    nextButtonText: ``,
    prevButtonText: ``,
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,

    pageImage: '/static/apps/mmt-my-money-calendar/img/icon-job.png',
    subtitle: 'Tell us about your Paycheck',
    description: '',
    nextPaymentDueDateLabel: 'When do you expect to receive your next paycheck?',
    nextPaymentAmountLabel: 'How much do you expect your next paycheck to be?',
  },
  {
    step: 'Income',
    category: 'Child Support',
    screenNumber: 0,
    nextButtonText: ``,
    prevButtonText: ``,
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,
    pageImage: '/static/apps/mmt-my-money-calendar/img/icon-childsupport.png',
    subtitle: 'Tell us about your Child Support Income',
    description: 'This is where any additional description will go.',
    nextPaymentDueDateLabel: 'What day should you receive your Next Child Support payment?',
    nextPaymentAmountLabel: 'How much should your Child Support payment be?',
  },
  {
    step: 'Income',
    category: 'Disability Benefits',
    screenNumber: 0,
    nextButtonText: ``,
    prevButtonText: ``,
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,
    pageImage: '/static/apps/mmt-my-money-calendar/img/icon-disability.png',
    subtitle: 'Tell us about your Disability income',
    description: 'This is where any additional description will go.',
    nextPaymentDueDateLabel: 'What day should you receive your Next Disability payment?',
    nextPaymentAmountLabel: 'How much should your Disability payment be?',
  },
  {
    step: 'Income',
    category: 'SNAP',
    screenNumber: 0,
    nextButtonText: ``,
    prevButtonText: ``,
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,
    pageImage: '/static/apps/mmt-my-money-calendar/img/icon-snap.png',
    subtitle: 'Tell us about your SNAP income',
    description: 'This is where any additional description will go.',
    nextPaymentDueDateLabel: 'What day should you receive your Next SNAP payment?',
    nextPaymentAmountLabel: 'How much should your SNAP payment be?',
  },
  {
    step: 'Income',
    category: 'TANF',
    screenNumber: 0,
    nextButtonText: ``,
    prevButtonText: ``,
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,
    pageImage: '/static/apps/mmt-my-money-calendar/img/icon-tanf.png',
    subtitle: 'Tell us about your TANF income',
    description: 'This is where any additional description will go.',
    nextPaymentDueDateLabel: 'What day should you receive your Next TANF payment?',
    nextPaymentAmountLabel: 'How much should your TANF payment be?',
  },
  {
    step: 'Income',
    category: 'Other',
    screenNumber: 0,
    nextButtonText: ``,
    prevButtonText: ``,
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,
    pageImage: '/static/apps/mmt-my-money-calendar/img/icon-otherGovt.png',
    subtitle: 'Describe your other income.',
    description: 'This is where any additional description will go.',
    nextPaymentDueDateLabel: 'What day should you receive your Next Other payment?',
    nextPaymentAmountLabel: 'How much should your Other payment be?',
  },
  {
    step: 'Expense',
    category: 'Housing',
    screenNumber: 0,
    nextButtonText: ``,
    prevButtonText: ``,
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,
    pageImage: '/static/apps/mmt-my-money-calendar/img/icon-housing.png',
    subtitle: 'Tell us about your Housing Costs',
    description: 'This is where any additional description will go.',
    nextPaymentDueDateLabel: 'What day is your Next housing payment due?',
    nextPaymentAmountLabel: 'How much do you pay each month for housing (rent or mortgage)?',
  },
  {
    step: 'Expense',
    category: 'Transportation',
    screenNumber: 0,
    nextButtonText: ``,
    prevButtonText: ``,
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,
    pageImage: '/static/apps/mmt-my-money-calendar/img/icon-housing.png',
    subtitle: 'Tell us about your Transportation Costs',
    description: 'This is where any additional description will go.',
    nextPaymentDueDateLabel: 'What day is your Next housing payment due?',
    nextPaymentAmountLabel: 'How much do you pay each month for housing (rent or mortgage)?',
  },
  {
    step: 'Expense',
    category: 'Groceries',
    screenNumber: 0,
    nextButtonText: ``,
    prevButtonText: ``,
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,
    pageImage: '/static/apps/mmt-my-money-calendar/img/icon-groceries.png',
    subtitle: 'Tell us how much you spend on Groceries',
    description: 'This is where any additional description will go.',
    nextPaymentDueDateLabel: 'What day is your Next housing payment due?',
    nextPaymentAmountLabel: 'How much do you pay each month for housing (rent or mortgage)?',
  },
  {
    step: 'Expense',
    category: 'Entertainment',
    screenNumber: 0,
    nextButtonText: ``,
    prevButtonText: ``,
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,
    pageImage: '/static/apps/mmt-my-money-calendar/img/icon-entertainment.png',
    subtitle: 'Tell us about your Entertainment Costs',
    description: 'This is where any additional description will go.',
    nextPaymentDueDateLabel: 'What day is your Next housing payment due?',
    nextPaymentAmountLabel: 'How much do you pay each month for housing (rent or mortgage)?',
    nextRoute: `/wizard/expense-summary`,
    nextButtonText: `Let's look at your expense summary`,
  },
  {
    step: 'Expense',
    category: 'Phone',
    screenNumber: 0,
    nextButtonText: ``,
    prevButtonText: ``,
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,
    pageImage: '/static/apps/mmt-my-money-calendar/img/icon-phone.png',
    subtitle: 'Tell us about your phone costs',
    description: 'This is where any additional description will go.',
    nextPaymentDueDateLabel: 'What day is your next phone bill due?',
    nextPaymentAmountLabel: 'How much do you pay each month for your phone(s)?',
    nextRoute: `/wizard/expense-summary`,
    nextButtonText: `Let's look at your expense summary`,
  },
  {
    step: 'Expense',
    category: 'Childcare',
    screenNumber: 0,
    nextButtonText: ``,
    prevButtonText: ``,
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,
    pageImage: '/static/apps/mmt-my-money-calendar/img/icon-childcare.png',
    subtitle: 'Tell us about your childcare costs',
    description: 'This is where any additional description will go.',
    nextPaymentDueDateLabel: 'What day is your childcare payment due?',
    nextPaymentAmountLabel: 'How much do you pay each month for housing (rent or mortgage)?',
    nextRoute: `/wizard/expense-summary`,
    nextButtonText: `Let's look at your expense summary`,
  },
];
