export const StepScreenDetails = [
  {
    step: 'Beginning Balance',
    category: 'Step',
    screenNumber: 1000,
    nextButtonText: 'Lets add the inputs for your cash on hand.',
    prevButtonText: '',
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,
    pageImage: '/static/apps/mmt-my-money-calendar/img/starting_balance.png',
    stepTitle: 'Lets look at at the cash you have on hand',
    description: 'check off those that you currently have',
  },
  {
    step: 'Income',
    category: 'Step',
    screenNumber: 1001,
    nextButtonText: 'Lets add the inputs for your income.',
    prevButtonText: '',
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,
    pageImage: '/static/apps/mmt-my-money-calendar/img/income-img.png',
    stepTitle: 'Tell us about your Income',
    description: 'check off those that you currently have',
    categoryOptions: '',
  },
  {
    step: 'Expenses',
    category: 'Step',
    screenNumber: 1002,
    nextButtonText: 'Lets add the inputs for your expenses.',
    prevButtonText: '',
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-input-screen`,
    pageImage: '/static/apps/mmt-my-money-calendar/img/expense-img.png',
    stepTitle: 'Tell us about your Expenses',
    description: 'check off those that you currently have',
  },
];

export const StepSummaryDetails = [
  {
    step: 'Beginning Balance',
    category: 'Step Summary',
    screenNumber: 1000,
    nextButtonText: 'Great work!  Now lets add your income.',
    prevButtonText: '',
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-selection-screen`,
    calendarImage: '/static/apps/mmt-my-money-calendar/img/jan-month-beg-balance.png',
    subtitle: 'Yeah!  You added some details on yhour Beginning Balance.',
    description: 'You have added the following',
    totalsSummary: 'totals summary',
  },
  {
    step: 'Income',
    category: 'Step Summary',
    screenNumber: 1001,
    nextButtonText: 'Great work!  Now, lets add your Expenses.',
    prevButtonText: '',
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-selection-screen`,
    calendarImage: '/static/apps/mmt-my-money-calendar/img/jan-month-beg-balance.png',
    subtitle: 'Yeah!  You added some details on yhour Beginning Balance.',
    description: 'You have added the following',
  },
  {
    step: 'Expenses',
    category: 'Step Summary',
    screenNumber: 1002,
    nextButtonText: 'Lets see the payoff!',
    prevButtonText: '',
    nextRoute: `/wizard/category-input-screen`,
    prevRoute: `/wizard/category-selection-screen`,
    calendarImage: '/static/apps/mmt-my-money-calendar/img/jan-month-beg-balance.png',
    subtitle: 'Yeah!  You added some details on yhour Beginning Balance.',
    description: 'You have added the following',
  },
];
