# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 18:12
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0028_auto_20190510_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='sections',
            field=wagtail.wagtailcore.fields.StreamField([('section', wagtail.wagtailcore.blocks.StructBlock([('section_heading', wagtail.wagtailcore.blocks.CharBlock(max_length=255)), ('section_anchor', wagtail.wagtailcore.blocks.CharBlock(max_length=255)), ('section_links', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([('heading', wagtail.wagtailcore.blocks.CharBlock(blank=True, max_length=255, required=False)), ('summary', wagtail.wagtailcore.blocks.TextBlock(blank=True, required=False)), ('link', wagtail.wagtailcore.blocks.StructBlock([('text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('url', wagtail.wagtailcore.blocks.CharBlock(required=True))]))])))]))]),
        ),
    ]
